/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/modelFiles/arcReacter.glb");
  return (
    <group ref={props.meshRef} {...props} dispose={null}>
      <group position={[-0.52, -1.58, 0.66]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[-0.03, -0.06, 0.03]}
        scale={[0.83, 0.83, 0.83]}
      />
      {/* <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["default"]}
        position={[-0.76, 0.88, 0.03]}
      /> */}
      <mesh
        geometry={nodes.Cube001_1.geometry}
        material={nodes.Cube001_1.material}
      />
      <mesh
        geometry={nodes.Cube001_2.geometry}
        material={materials["Material.007"]}
      />
      <mesh
        geometry={nodes.Cube001_3.geometry}
        material={materials["Material.008"]}
      />
      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials["Material.004"]}
        position={[-0.08, -0.36, 0.03]}
        scale={[1.4, 1.4, 1.4]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0.47, -0.06, 0.05]}
        scale={[0.18, 0.18, 0.18]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-0.35, -0.09, 0.53]}
        rotation={[-Math.PI, -1.13, -Math.PI]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-0.49, -0.09, -0.52]}
        rotation={[-Math.PI, 0.97, -Math.PI]}
        scale={[0.18, 0.18, 0.18]}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials["Material.011"]}
        position={[-0.13, -0.2, 0.02]}
        scale={[0.51, 0.18, 0.51]}
      />
    </group>
  );
}

useGLTF.preload("/arcReacterD.glb");
