/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  // const group = useRef();
  const { nodes, materials } = useGLTF("/modelFiles/ironManHelemt-D.glb");
  return (
    <group ref={props.meshRef} {...props} dispose={null}>
      <pointLight
        intensity={2}
        position={[1, 5, 5]}
        decay={2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.STL_uploads_files_625930_iron_man_helmet.geometry}
        material={nodes.STL_uploads_files_625930_iron_man_helmet.material}
        position={[0, -4.57, -1.25]}
        rotation={[0.1, 0.04, -0.02]}
        scale={[0.06, 0.05, 0.06]}
      />
      <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.06, 0, -0.12]}
        rotation={[1.57, 0.04, 0]}
        scale={[2.98, 0.28, 3.48]}
      />
    </group>
  );
}

useGLTF.preload("/ironManHelemt-D.glb");
