/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/modelFiles/mjolnir_2-D.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[-2.8, 5.74, 2.53]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.006"]}
        position={[-2.8, 2.11, 2.53]}
        scale={[0.57, 3.56, 0.66]}
      />
      <mesh
        geometry={nodes.BezierCircle.geometry}
        material={nodes.BezierCircle.material}
        position={[0.14, 0.18, 1.56]}
        scale={[0.51, 0.51, 0.51]}
      />
    </group>
  );
}

useGLTF.preload("/mjolnir_2-D.glb");
