/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/modelFiles/mjolnir.glb");
  return (
    <group ref={props.meshRef} {...props} dispose={null}>
      {/* <group position={[-0.52, -1.58, 0.66]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group> */}
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.011"]}
        position={[-2.8, 5.74, 2.53]}
      />
      <group position={[-2.8, 2.11, 2.53]} scale={[0.57, 3.56, 0.66]}>
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.006"]}
        />
        <points
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        geometry={nodes.BezierCircle.geometry}
        material={materials["Material.009"]}
        position={[0.14, 0.18, 1.56]}
        scale={[0.51, 0.51, 0.51]}
      />
    </group>
  );
}

useGLTF.preload("/mjolnirD2.glb");
