/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  // const group = useRef();
  const { nodes, materials } = useGLTF("/modelFiles/shield.glb");
  return (
    <group ref={props.meshRef} {...props} dispose={null}>
      <group position={[-1.41, 4.2, 3.22]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.67, 3.9, 3.91]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      {/* <group position={[-2.32, 5.59, 3.92]}>
        <directionalLight
          intensity={1}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-2.33, 5.68, 2.37]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.84, 5.49, 4.2]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.62, 6.26, 4.37]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.13, 7.02, 3.39]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.6, 5.38, 3.06]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.41, 4.57, 3.3]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.67, 4.27, 3.99]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.32, 5.96, 4]}>
        <directionalLight
          intensity={1}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group> */}
      {/* <group position={[-2.33, 6.05, 2.44]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.83, 5.86, 4.28]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.62, 6.64, 4.45]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.13, 7.39, 3.47]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.59, 5.76, 3.14]}>
        <pointLight intensity={2} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group> */}
      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Circle002_1.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Circle002_2.geometry}
        material={materials["Material.004"]}
      />
      <mesh
        geometry={nodes.Circle002_3.geometry}
        material={materials["Material.005"]}
      />
    </group>
  );
}

useGLTF.preload("/modelFiles/shield.glb");
