/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/modelFiles/sp-D.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[-0.21, -0.26, -0.03]}
        rotation={[-1.59, 0, -3.12]}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials["Material.002"]}
        position={[-0.2, 0.62, -0.01]}
        rotation={[-1.59, 0, -3.12]}
        scale={[0.46, 0.46, 0.46]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-1.16, -0.24, -0.01]}
        rotation={[-1.59, 0, -3.12]}
        scale={[0.03, 0.07, 0.5]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-1.02, 0.36, -0.03]}
        rotation={[-1.8, 1.04, -2.89]}
        scale={[0.21, 0.21, 0.21]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-0.89, 0.63, -0.04]}
        rotation={[-1.59, 0, -3.12]}
        scale={[-0.05, 0.34, 0.18]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[-0.08, 0.22, 0.28]}
        rotation={[-1.59, -0.15, -3.12]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[-0.18, 0.75, 0.27]}
        rotation={[-1.59, 0, -3.12]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[-1.42, -0.33, -0.01]}
        rotation={[-1.59, 0, -3.12]}
        scale={[0.04, 0.08, 0.55]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[-1.27, 0.33, -0.03]}
        rotation={[-1.8, 1.04, -2.89]}
        scale={[0.23, 0.23, 0.23]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[-1.12, 0.64, -0.05]}
        rotation={[-1.59, 0, -3.12]}
        scale={[-0.06, 0.38, 0.2]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[-0.22, 0.18, 0.3]}
        rotation={[-1.59, -0.15, -3.12]}
        scale={[0.06, 1.11, -0.27]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[-0.33, 0.77, 0.29]}
        rotation={[-1.59, 0, -3.12]}
        scale={[0.04, 1.11, 0.16]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={nodes.Plane010.material}
        position={[0.81, -0.26, 0.03]}
        rotation={[-1.59, 0, 0.03]}
        scale={[0.03, 0.07, 0.5]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[0.68, 0.33, 0.02]}
        rotation={[-1.46, -0.88, 0.19]}
        scale={[0.21, 0.21, 0.21]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[0.54, 0.62, 0.02]}
        rotation={[-1.59, -0.03, 0.03]}
        scale={[-0.05, 0.34, 0.18]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[-0.26, 0.17, -0.28]}
        rotation={[-1.59, 0.13, 0.03]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[-0.18, 0.71, -0.29]}
        rotation={[-1.59, -0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={nodes.Plane015.material}
        position={[1.04, -0.33, 0.04]}
        rotation={[-1.59, 0, 0.03]}
        scale={[0.04, 0.08, 0.55]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[0.92, 0.33, 0.03]}
        rotation={[-1.5, -0.73, 0.16]}
        scale={[0.23, 0.23, 0.23]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[0.77, 0.64, 0.03]}
        rotation={[-1.59, -0.01, 0.03]}
        scale={[-0.06, 0.38, 0.2]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={nodes.Plane018.material}
        position={[-0.12, 0.16, -0.3]}
        rotation={[-1.6, 0.14, 0.03]}
        scale={[0.06, 1.11, -0.27]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={nodes.Plane019.material}
        position={[-0.02, 0.76, -0.32]}
        rotation={[-1.59, -0.01, 0.03]}
        scale={[0.04, 1.11, 0.16]}
      />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={nodes.Plane020.material}
        position={[-0.13, -0.12, 0.06]}
        rotation={[1.55, 0, 3.14]}
        scale={[1.27, 1.05, 1]}
      />
    </group>
  );
}

useGLTF.preload("/sp-D.glb");
