/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/modelFiles/spiderLogo.glb");
  return (
    <group ref={props.meshRef} {...props} dispose={null}>
      <group position={[4.08, 2.13, 5.69]} rotation={[-2.84, 0.88, -2.05]}>
        <pointLight intensity={10} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[1.06, 0.62, 3.9]} rotation={[-2.84, 0.88, -2.05]}>
        <pointLight intensity={10} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[0, -0.09, -0.49]}
        rotation={[-0.01, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={nodes.Circle003.material}
        position={[0, -0.04, 0.4]}
        rotation={[-0.01, 0, 0]}
        scale={[0.46, 0.46, 0.46]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0.88, -0.1, -0.49]}
        rotation={[-0.01, 0, 0]}
        scale={[0.03, 0.07, 0.5]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[0.74, -0.09, 0.11]}
        rotation={[0.15, -1.04, 0.2]}
        scale={[0.21, 0.21, 0.21]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[0.6, -0.09, 0.38]}
        rotation={[-0.01, 0, 0]}
        scale={[-0.05, -0.01, 0.18]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[-0.19, 0.24, -0.04]}
        rotation={[-0.01, 0.15, 0]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[-0.1, 0.24, 0.49]}
        rotation={[-0.01, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[1.12, -0.11, -0.55]}
        rotation={[-0.01, 0, 0]}
        scale={[0.04, 0.08, 0.55]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[0.97, -0.1, 0.11]}
        rotation={[0.15, -1.04, 0.2]}
        scale={[0.23, 0.23, 0.23]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[0.82, -0.1, 0.41]}
        rotation={[-0.01, 0, 0]}
        scale={[-0.06, 0.38, 0.2]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[-0.07, 0.26, -0.05]}
        rotation={[-0.01, 0.15, 0]}
        scale={[0.06, 1.11, -0.27]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[0.04, 0.26, 0.54]}
        rotation={[-0.01, 0, 0]}
        scale={[0.04, 1.11, 0.16]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={nodes.Plane010.material}
        position={[-0.88, -0.01, -0.49]}
        rotation={[-0.01, 0, -Math.PI]}
        scale={[0.03, 0.07, 0.5]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[-0.74, 0, 0.11]}
        rotation={[-0.12, 0.89, -2.99]}
        scale={[0.21, 0.21, 0.21]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[-0.6, 0.01, 0.4]}
        rotation={[-0.02, 0.03, -3.14]}
        scale={[-0.05, 0.34, 0.18]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[0.18, -0.33, -0.04]}
        rotation={[-0.02, -0.12, -3.14]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[0.1, -0.35, 0.5]}
        rotation={[-0.02, 0.03, -3.14]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={nodes.Plane015.material}
        position={[-1.14, 0, -0.55]}
        rotation={[-0.01, 0, -Math.PI]}
        scale={[0.04, 0.08, 0.55]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[-0.98, 0.02, 0.11]}
        rotation={[-0.09, 0.74, -3.01]}
        scale={[0.23, 0.23, 0.23]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[-0.83, 0.02, 0.42]}
        rotation={[-0.01, 0.01, -3.14]}
        scale={[-0.06, 0.38, 0.2]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={nodes.Plane018.material}
        position={[0.05, -0.35, -0.05]}
        rotation={[-0.01, -0.14, -3.14]}
        scale={[0.06, 1.11, -0.27]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={nodes.Plane019.material}
        position={[-0.05, -0.37, 0.55]}
        rotation={[-0.01, 0.01, -3.14]}
        scale={[0.04, 1.11, 0.16]}
      />
    </group>
  );
}

useGLTF.preload("/spiderLogoDraco3.glb");
